### PR TITLE
Reduce code duplication with helper function 'command_execute'

### PR DESCRIPTION
**Pull request by Vinalti**
## Edits
 - **Add `command_execute` function**
    _factorize duplicated code into one function for simplicity sake_

## Context
The same code was repeated many times to make a request to the API (adding to the risk of discrepancy) :
```py
    url=f"https://api.switch-bot.com/v1.1/devices/{deviceId}/commands"
    myjson= {"command": "...", "commandType": "command"}
    # ...
    requestHelper(url,myjson,headers_dict)
```

## Result
This pull request regroup that into one function  : 
```py
def command_execute(headers, device_id, command, parameter=None, custom=False):
    url=f"https://api.switch-bot.com/v1.1/devices/{device_id}/commands"
    data= {"command": command, "commandType":"command"}
    if parameter is not None:
      data["parameter"] = parameter
    if custom:
      data["commandType"] = 'customize'
    requestHelper(url, data, headers)
```

### CODE REVIEW

**Comment by SiriosDev** [comment]
as you suggested I opened more branches and moved this PR under dev

**Review by Vinalti — COMMENTED** [review]
I fixed this PR. it is tested and operational.

**Review by SiriosDev — COMMENTED** [review]
I have an idea, let's do it even cleaner, since the header variable id also repeated, we can remove the parameter and integrate the function call into the command executor

**Comment by Vinalti** [comment]
Well, somehow I coulnd't get it to work with the authentication inside the `send_command` or `requestHelper`.
The pyscript variable is only reachable from a `@service` decorated function... 
I tried also passing the `app_config` as a param, of the `command_execute` but the command is not executed and I don't get anything in the logs... Not sure what's the problem on this one.
Did you try something ?
I'd go for integrating it as it is, and then we can try to integrate the `auth` part in another PR later on, so we can just move on. what do you think ?

**Comment by SiriosDev** [comment]
> Well, somehow I coulnd't get it to work with the authentication inside the `send_command` or `requestHelper`. The pyscript variable is only reachable from a `@service` decorated function... I tried also passing the `app_config` as a param, of the `command_execute` but the command is not executed and I don't get anything in the logs... Not sure what's the problem on this one. Did you try something ? I'd go for integrating it as it is, and then we can try to integrate the `auth` part in another PR later on, so we can just move on. what do you think ?

yes I agree I will proceed to merge

**Pull request merged**
